### ISSUE TITLE
Could you please share your place365 pre-trained model?

### ISSUE THREAD

**Issue by TheSunWillRise** [google-research/dp-imagenet#4]
Hi, thanks for your great job. 
I'm trying to train models on imagenet with DP. However, it is too time-consuming for me to pretrain the model on place365.
Could you please share your place365 pre-trained model? I would be very appreciative.

**Comment by AlexeyKurakin** [comment]
Hi, 
I expect to release the checkpoints some time soon. I'm working on getting necessary approvals to do this.

**Comment by AlexeyKurakin** [comment]
I added links to the models pre-trained on Places365 on the bottom of README.md
